# PCHEM HW#

### Question 12-2 from Schrier Book

In [1]:
import numpy as np

def generate_initial_configuration(rows, cols):
    """
    Generate an initial configuration of spins in a 2D square lattice.

    Parameters:
    - rows: Number of rows in the lattice
    - cols: Number of columns in the lattice

    Returns:
    - spin_configuration: 2D NumPy array representing the initial spin configuration
    """

    # Create an empty 2D array to represent the lattice
    spin_configuration = np.zeros((rows, cols), dtype=int)

    # Set the left half of the system to +1 and the right half to -1
    mid_col = cols // 2
    spin_configuration[:, :mid_col] = 1
    spin_configuration[:, mid_col:] = -1

    return spin_configuration

# Example usage for a 6x6 lattice
rows, cols = 6, 6
initial_spin_configuration = generate_initial_configuration(rows, cols)

# Print the initial spin configuration
print(initial_spin_configuration)

[[ 1  1  1 -1 -1 -1]
 [ 1  1  1 -1 -1 -1]
 [ 1  1  1 -1 -1 -1]
 [ 1  1  1 -1 -1 -1]
 [ 1  1  1 -1 -1 -1]
 [ 1  1  1 -1 -1 -1]]


### Question 12-4 from Schrier Book

In [4]:
def create_random_spin_configuration(rows, cols, num_positive_spins):
    """
    Create a random spin configuration for a 2D lattice with a specified number of +1 spins.

    Parameters:
    - rows: Number of rows in the lattice
    - cols: Number of columns in the lattice
    - num_positive_spins: Number of spins with sigma_i = +1

    Returns:
    - spin_configuration: 2D NumPy array representing the random spin configuration
    """

    # Create an empty 2D array to represent the lattice
    spin_configuration = -1 * np.ones((rows, cols), dtype=int) # Every value will start be being -1, then we will change randomly 10 values to 1

    # Randomly select positions for positive spins
    positive_spins_indices = np.random.choice(rows * cols, num_positive_spins, replace=False)
    positive_spins_positions = np.unravel_index(positive_spins_indices, (rows, cols))

    # Set the selected positions to +1
    spin_configuration[positive_spins_positions] = 1

    return spin_configuration

# Example usage for a 10x10 lattice with 10 +1 spins
rows, cols = 10, 10
num_positive_spins = 10
random_spin_configuration = create_random_spin_configuration(rows, cols, num_positive_spins)

# Print the random spin configuration
print(random_spin_configuration)

[[-1  1 -1  1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1  1]
 [ 1 -1 -1 -1 -1 -1  1 -1 -1  1]
 [-1  1  1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1  1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1  1 -1 -1]]
